name: unit-tests

on:
  pull_request:
    branches: [ develop, main ]
jobs:
  Unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: run unit-tests
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: unit-tests
          distributions-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
